// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urebctifhcxphqbhwrjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyZWJjdGlmaGN4cGhxYmh3cmpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NTA2NDUsImV4cCI6MjA3MjEyNjY0NX0.W7TNWyXDxH2U84KnK6TJ3QoVXGg49v7eVEdkXZ1-r0Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});